In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import pymysql
import time
from collections import Counter
from math import sqrt
from sqlalchemy import create_engine

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

pymysql.install_as_MySQLdb()

In [38]:
engine = create_engine('mysql://root:12345678@localhost:3306/household')
with engine.begin() as connection:
    df = pd.read_sql("select * from household.clean_dataset", con=connection, index_col='dt')

In [39]:
df.shape

(21996, 7)

In [40]:
df.head()

Global_active_power  Global_reactive_power  Voltage  \
dt                                                                         
2006-12-16 17:24:00                4.216                  0.418   234.84   
2006-12-16 17:25:00                5.360                  0.436   233.63   
2006-12-16 17:26:00                5.374                  0.498   233.29   
2006-12-16 17:27:00                5.388                  0.502   233.74   
2006-12-16 17:28:00                3.666                  0.528   235.68   

                     Global_intensity  Sub_metering_1  Sub_metering_2  \
dt                                                                      
2006-12-16 17:24:00              18.4             0.0             1.0   
2006-12-16 17:25:00              23.0             0.0             1.0   
2006-12-16 17:26:00              23.0             0.0             2.0   
2006-12-16 17:27:00              23.0             0.0             1.0   
2006-12-16 17:28:00              15.8             0.0             1.0   

                     Sub_metering_3  
dt                                   
2006-12-16 17:24:00            17.0  
2006-12-16 17:25:00            16.0  
2006-12-16 17:26:00            17.0  
2006-12-16 17:27:00            17.0  
2006-12-16 17:28:00            17.0

In [41]:
X = df.drop("Sub_metering_3", axis=1)
y = df["Sub_metering_3"]

In [42]:
np.random.seed(3005)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2022)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16497, 6), (5499, 6), (16497,), (5499,))

In [43]:
print(X_train)

                     Global_active_power  Global_reactive_power  Voltage  \
dt                                                                         
2006-12-30 06:50:00                1.442                  0.176   246.29   
2006-12-23 15:05:00                2.330                  0.106   242.48   
2006-12-30 09:48:00                4.722                  0.142   239.69   
2006-12-19 19:14:00                1.354                  0.072   241.43   
2006-12-24 02:42:00                0.212                  0.000   248.07   
...                                  ...                    ...      ...   
2006-12-26 10:45:00                4.398                  0.052   236.79   
2006-12-20 00:04:00                0.976                  0.064   245.18   
2006-12-28 05:21:00                0.238                  0.066   248.01   
2006-12-17 14:08:00                1.938                  0.120   244.51   
2006-12-31 13:37:00                3.454                  0.072   237.50   

           

In [44]:
neigh = KNeighborsRegressor(n_neighbors=9)
neigh.fit(X_train, y_train)

y_pred = neigh.predict(X_test)

rmse = sqrt(mean_squared_error(y_test, y_pred))
rmse

5.46743553837798

In [45]:
X_train = X_train.to_numpy()
y_train = y_train.to_numpy()
X_test = X_test.to_numpy()
y_test = y_test.to_numpy()

print(X_train)

[[1.4420e+00 1.7600e-01 2.4629e+02 5.8000e+00 0.0000e+00 0.0000e+00]
 [2.3300e+00 1.0600e-01 2.4248e+02 9.8000e+00 0.0000e+00 0.0000e+00]
 [4.7220e+00 1.4200e-01 2.3969e+02 1.9600e+01 0.0000e+00 3.7000e+01]
 ...
 [2.3800e-01 6.6000e-02 2.4801e+02 1.0000e+00 0.0000e+00 0.0000e+00]
 [1.9380e+00 1.2000e-01 2.4451e+02 8.0000e+00 0.0000e+00 0.0000e+00]
 [3.4540e+00 7.2000e-02 2.3750e+02 1.4400e+01 0.0000e+00 0.0000e+00]]


In [46]:
def KNN(X_train, X_test, y_train, k):
    # số lượng dữ liệu test
    num_test = X_test.shape[0] 
    # số lượng dữ liệu train
    num_train = X_train.shape[0]
    # ma trận tính k/c mỗi điểm trong tập test với tất cả điểm trong tập train
    y_pred = np.zeros((num_test, num_train))
    for i in range(num_test):
        for j in range(num_train):
            y_pred[i,j] = np.sqrt(np.sum(np.power(X_test[i,:]-X_train[j,:],2)))
            
    results = []
    
    #sắp xếp khoảng cách tăng dần
    for i in range(len(y_pred)):
        zipped = zip(y_pred[i,:], y_train)
        res = sorted(zipped, key = lambda x:x[0])
        results_topk = res[:k]
        # Đếm số lượng của mỗi class
        classes = {}
        for _,j in results_topk:
            j = int(j)
            if j not in classes:
                classes[j] = 1
            else:
                classes[j] = classes[j] + 1
        # trả về class có số lượng nhiều nhất
        results.append(max(classes, key = classes.get))
    return np.array(results)

results = KNN(X_train, X_test, y_train, 9)

In [50]:
def Accuracy(y_test, y_pred):
    dem = 0
    for i in range(len(y_test)):
        if y_test[i] == y_pred[i]:
            dem += 1
    return dem/len(y_test)*100

# in accuracy
print(Accuracy(results,y_test))

75.59556282960538
